import { randomUUID } from "node:crypto";
import { parsePossiblyBrokenJson } from "./json-utils.js";
import { createAiProvider } from "./providers.js";
import { evaluateConfig } from "./evaluation-engine.js";
import { repairAndValidateConfig } from "./repair-engine.js";
import type { AiProvider, PipelineRunResult, PipelineStage, PipelineStageStatus } from "./types.js";

function now(): string {
  return new Date().toISOString();
}

async function timedStage<T>(
  stages: PipelineStage[],
  name: string,
  run: () => Promise<T>,
  successMessage: (result: T) => string,
  warning?: (result: T) => string | undefined
): Promise<T> {
  const started = Date.now();
  const startedAt = now();

  try {
    const result = await run();
    const warningMessage = warning?.(result);
    const completedAt = now();
    stages.push({
      name,
      status: warningMessage ? "warning" : "success",
      startedAt,
      completedAt,
      durationMs: Date.now() - started,
      message: warningMessage ?? successMessage(result)
    });
    return result;
  } catch (error: unknown) {
    const completedAt = now();
    stages.push({
      name,
      status: "error" satisfies PipelineStageStatus,
      startedAt,
      completedAt,
      durationMs: Date.now() - started,
      message: error instanceof Error ? error.message : "Stage failed"
    });
    throw error;
  }
}

export class PipelineEngine {
  constructor(private readonly provider: AiProvider = createAiProvider()) {}

  async run(input: { prompt: string; seedConfig?: unknown }): Promise<PipelineRunResult> {
    const stages: PipelineStage[] = [];
    const prompt = input.prompt.trim();

    await timedStage(
      stages,
      "intake",
      async () => prompt,
      () => "Prompt accepted.",
      (value) => (value.length < 8 ? "Prompt is short; generated config may be generic." : undefined)
    );

    const draft = await timedStage(
      stages,
      "draft",
      async () => this.provider.generateConfigDraft({ prompt, seedConfig: input.seedConfig }),
      (result) => `Draft generated by ${result.provider}.`
    );

    const parsed = await timedStage(
      stages,
      "parse",
      async () => parsePossiblyBrokenJson(draft.text),
      () => "Draft JSON parsed.",
      (result) => (result.repaired ? "Draft JSON needed syntax repair before parsing." : undefined)
    );

    const repair = await timedStage(
      stages,
      "repair",
      async () => repairAndValidateConfig(parsed.value),
      (result) => `Config normalized with ${result.changes.length} repair change(s).`,
      (result) => (result.findings.some((finding) => finding.severity === "error") ? "Config has blocking findings after repair." : undefined)
    );

    const evaluation = await timedStage(
      stages,
      "evaluate",
      async () => evaluateConfig(repair.config),
      (result) => `Evaluation completed with grade ${result.grade}.`,
      (result) => (result.blockers.length > 0 ? "Evaluation found blockers." : undefined)
    );

    return {
      runId: randomUUID(),
      prompt,
      provider: draft.provider,
      model: draft.model,
      stages,
      rawDraft: draft.text,
      config: repair.config,
      repair,
      evaluation
    };
  }
}
